import dataclasses
from datetime import datetime


@dataclasses.dataclass(frozen=True)
class JobPost:
    """The normalized payload generated by any JobBoard adapter."""
    id: str  # Uniquely scoped to the board, e.g., "linkedin_12345"
    title: str
    company: str
    url: str
    board: str
    published_at: datetime | None = None
